app/apis/urls.py
from django.urls import path

from apis.views import GetListAllNew

app_name = 'api'

urlpatterns = [
    path('list/all/new/', GetListAllNew.as_view())
]

app/config/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from django.urls import path, include

from web_admin.views import SignUpView, LandingPageView

urlpatterns = [
    path('ask_admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='base'),
    path('', include('web_admin.urls', namespace='web_admin')),
    path('api/v1/new/', include('apis.urls', namespace='apis')),
    path('signup', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

app/web_admin/urls.py
from django.urls import path

from web_admin.views import CreateNew

app_name = 'web_admin'

urlpatterns = [
    path('web/', CreateNew.as_view(), name='create_new'),
]

app/apis/models.py
from django.db import models

# Create your models here.

app/web_admin/models.py
from django.contrib.auth.models import User
from django.db import models


class New(models.Model):
    '''New - сущность новость'''

    class Meta:
        db_table = 'news'
        verbose_name_plural = 'Новости'
        verbose_name = 'Новость'
        ordering = ("-date",)

    date = models.DateField(verbose_name='Дата(d.m.Y)')
    subject = models.CharField(verbose_name='Заголовок новости', max_length=256)
    content = models.TextField(verbose_name='Содержание новости')
    user = models.ForeignKey(User, verbose_name='Пользователь', related_name='news', on_delete=models.CASCADE)

    def __str__(self):
        return self.subject

app/web_admin/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

from web_admin.models import New


User = get_user_model()


class NewCreateForm(forms.ModelForm):
    class Meta:
        model = New
        fields = '__all__'


class CustomUserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)
        field_classes = {'username': UsernameField}

app/apis/views.py
from rest_framework.generics import ListAPIView

from apis.serializers import NewSerializer
from web_admin.models import New


class GetListAllNew(ListAPIView):
    serializer_class = NewSerializer

    def get_queryset(self):
        return New.objects.all()

app/web_admin/views.py
from django.urls import reverse
from django.views.generic import CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from web_admin.forms import NewCreateForm
from web_admin.forms import CustomUserCreateForm


class LandingPageView(TemplateView):
    template_name = "base.html"


class CreateNew(LoginRequiredMixin, CreateView):
    form_class = NewCreateForm
    template_name = 'web_admin/create_new.html'
    success_url = '/'


class SignUpView(CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreateForm

    def get_success_url(self):
        return reverse('login')

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
</head>
<body>
    <section class="selection">
        {% include 'navbar.html' %}
        <div class="container">
        {% block content %}
        {% endblock content %}
        </div>
    </section>

    <footer class="footer">
            <h6 class="is-size-4 mb-4">copyright(c) Askvart  2022 ver.002</h6>
    </footer>

</body>
</html>

app/templates/navbar.html
<header>
    <div>
        Logged in as: {{ request.user.username }}
    </div>
    <div>
      <a href="{% url 'login' %}">
          Login
      </a>
      <a href="{% url 'signup' %}">
          Signup
      </a>
      <a href="{% url 'logout' %}">
          Logout
      </a>
    </div>

</header>
<div class="container">
    <div class="is-size-4 mb-4">
          <a href="{% url 'web_admin:create_new' %}">CreateNew</a>
    </div>
</div>
<br/>
    {% if request.user.is_authenticated %}
        <div class="container">
            <a href="/api/v1/new/list/all/new/">
                Смотреть все новсти через REST API
            </a>
        </div>
    {% endif %}

app/web_admin/templates/web_admin/create_new.html
{% extends "base.html" %}

{% block content %}

<h3 class="is-size-4 mb-4">Форма ввода новостей</h3>

<form method="post">
    {% csrf_token %}
    <table border="1">
        {{ form }}
    </table>
    <button class="button is-primary" type="submit">Add new </button>
</form>

{% endblock content %}